FROM nginx:alpine

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/nginx.conf

# Копируем нашу конфигурацию
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Копируем статические файлы фронтенда
COPY static/ /usr/share/nginx/html/

# Проверяем, что index.html существует
RUN ls -la /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]